#ifndef AIRPORT_BUILDER_H
#define AIRPORT_BUILDER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef AIRPORT_READER_H
#include "airport_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif

static const flatbuffers_voffset_t __gaia_airport_airlines_required[] = { 0 };
typedef flatbuffers_ref_t gaia_airport_airlines_ref_t;
static gaia_airport_airlines_ref_t gaia_airport_airlines_clone(flatbuffers_builder_t *B, gaia_airport_airlines_table_t t);
__flatbuffers_build_table(flatbuffers_, gaia_airport_airlines, 9)

static const flatbuffers_voffset_t __gaia_airport_airports_required[] = { 0 };
typedef flatbuffers_ref_t gaia_airport_airports_ref_t;
static gaia_airport_airports_ref_t gaia_airport_airports_clone(flatbuffers_builder_t *B, gaia_airport_airports_table_t t);
__flatbuffers_build_table(flatbuffers_, gaia_airport_airports, 15)

static const flatbuffers_voffset_t __gaia_airport_routes_required[] = { 0 };
typedef flatbuffers_ref_t gaia_airport_routes_ref_t;
static gaia_airport_routes_ref_t gaia_airport_routes_clone(flatbuffers_builder_t *B, gaia_airport_routes_table_t t);
__flatbuffers_build_table(flatbuffers_, gaia_airport_routes, 13)

#define __gaia_airport_airlines_formal_args ,\
  int64_t v0, int32_t v1, flatbuffers_string_ref_t v2, flatbuffers_string_ref_t v3,\
  flatbuffers_string_ref_t v4, flatbuffers_string_ref_t v5, flatbuffers_string_ref_t v6, flatbuffers_string_ref_t v7, flatbuffers_string_ref_t v8
#define __gaia_airport_airlines_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7, v8
static inline gaia_airport_airlines_ref_t gaia_airport_airlines_create(flatbuffers_builder_t *B __gaia_airport_airlines_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, gaia_airport_airlines, gaia_airport_airlines_file_identifier, gaia_airport_airlines_type_identifier)

#define __gaia_airport_airports_formal_args ,\
  int64_t v0, int32_t v1, flatbuffers_string_ref_t v2, flatbuffers_string_ref_t v3,\
  flatbuffers_string_ref_t v4, flatbuffers_string_ref_t v5, flatbuffers_string_ref_t v6, double v7,\
  double v8, int32_t v9, float v10, flatbuffers_string_ref_t v11,\
  flatbuffers_string_ref_t v12, flatbuffers_string_ref_t v13, flatbuffers_string_ref_t v14
#define __gaia_airport_airports_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11,\
  v12, v13, v14
static inline gaia_airport_airports_ref_t gaia_airport_airports_create(flatbuffers_builder_t *B __gaia_airport_airports_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, gaia_airport_airports, gaia_airport_airports_file_identifier, gaia_airport_airports_type_identifier)

#define __gaia_airport_routes_formal_args ,\
  int64_t v0, int64_t v1, int64_t v2, int64_t v3,\
  flatbuffers_string_ref_t v4, int32_t v5, flatbuffers_string_ref_t v6, int32_t v7,\
  flatbuffers_string_ref_t v8, int32_t v9, flatbuffers_string_ref_t v10, int32_t v11, flatbuffers_string_ref_t v12
#define __gaia_airport_routes_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11, v12
static inline gaia_airport_routes_ref_t gaia_airport_routes_create(flatbuffers_builder_t *B __gaia_airport_routes_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, gaia_airport_routes, gaia_airport_routes_file_identifier, gaia_airport_routes_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, gaia_airport_airlines_gaia_id, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), gaia_airport_airlines)
__flatbuffers_build_scalar_field(1, flatbuffers_, gaia_airport_airlines_al_id, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), gaia_airport_airlines)
__flatbuffers_build_string_field(2, flatbuffers_, gaia_airport_airlines_name, gaia_airport_airlines)
__flatbuffers_build_string_field(3, flatbuffers_, gaia_airport_airlines_alias, gaia_airport_airlines)
__flatbuffers_build_string_field(4, flatbuffers_, gaia_airport_airlines_iata, gaia_airport_airlines)
__flatbuffers_build_string_field(5, flatbuffers_, gaia_airport_airlines_icao, gaia_airport_airlines)
__flatbuffers_build_string_field(6, flatbuffers_, gaia_airport_airlines_callsign, gaia_airport_airlines)
__flatbuffers_build_string_field(7, flatbuffers_, gaia_airport_airlines_country, gaia_airport_airlines)
__flatbuffers_build_string_field(8, flatbuffers_, gaia_airport_airlines_active, gaia_airport_airlines)

static inline gaia_airport_airlines_ref_t gaia_airport_airlines_create(flatbuffers_builder_t *B __gaia_airport_airlines_formal_args)
{
    if (gaia_airport_airlines_start(B)
        || gaia_airport_airlines_gaia_id_add(B, v0)
        || gaia_airport_airlines_al_id_add(B, v1)
        || gaia_airport_airlines_name_add(B, v2)
        || gaia_airport_airlines_alias_add(B, v3)
        || gaia_airport_airlines_iata_add(B, v4)
        || gaia_airport_airlines_icao_add(B, v5)
        || gaia_airport_airlines_callsign_add(B, v6)
        || gaia_airport_airlines_country_add(B, v7)
        || gaia_airport_airlines_active_add(B, v8)) {
        return 0;
    }
    return gaia_airport_airlines_end(B);
}

static gaia_airport_airlines_ref_t gaia_airport_airlines_clone(flatbuffers_builder_t *B, gaia_airport_airlines_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (gaia_airport_airlines_start(B)
        || gaia_airport_airlines_gaia_id_pick(B, t)
        || gaia_airport_airlines_al_id_pick(B, t)
        || gaia_airport_airlines_name_pick(B, t)
        || gaia_airport_airlines_alias_pick(B, t)
        || gaia_airport_airlines_iata_pick(B, t)
        || gaia_airport_airlines_icao_pick(B, t)
        || gaia_airport_airlines_callsign_pick(B, t)
        || gaia_airport_airlines_country_pick(B, t)
        || gaia_airport_airlines_active_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, gaia_airport_airlines_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, gaia_airport_airports_gaia_id, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), gaia_airport_airports)
__flatbuffers_build_scalar_field(1, flatbuffers_, gaia_airport_airports_ap_id, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), gaia_airport_airports)
__flatbuffers_build_string_field(2, flatbuffers_, gaia_airport_airports_name, gaia_airport_airports)
__flatbuffers_build_string_field(3, flatbuffers_, gaia_airport_airports_city, gaia_airport_airports)
__flatbuffers_build_string_field(4, flatbuffers_, gaia_airport_airports_country, gaia_airport_airports)
__flatbuffers_build_string_field(5, flatbuffers_, gaia_airport_airports_iata, gaia_airport_airports)
__flatbuffers_build_string_field(6, flatbuffers_, gaia_airport_airports_icao, gaia_airport_airports)
__flatbuffers_build_scalar_field(7, flatbuffers_, gaia_airport_airports_latitude, flatbuffers_double, double, 8, 8, 0.0000000000000000, gaia_airport_airports)
__flatbuffers_build_scalar_field(8, flatbuffers_, gaia_airport_airports_longitude, flatbuffers_double, double, 8, 8, 0.0000000000000000, gaia_airport_airports)
__flatbuffers_build_scalar_field(9, flatbuffers_, gaia_airport_airports_altitude, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), gaia_airport_airports)
__flatbuffers_build_scalar_field(10, flatbuffers_, gaia_airport_airports_timezone, flatbuffers_float, float, 4, 4, 0.00000000f, gaia_airport_airports)
__flatbuffers_build_string_field(11, flatbuffers_, gaia_airport_airports_dst, gaia_airport_airports)
__flatbuffers_build_string_field(12, flatbuffers_, gaia_airport_airports_tztext, gaia_airport_airports)
__flatbuffers_build_string_field(13, flatbuffers_, gaia_airport_airports_type, gaia_airport_airports)
__flatbuffers_build_string_field(14, flatbuffers_, gaia_airport_airports_source, gaia_airport_airports)

static inline gaia_airport_airports_ref_t gaia_airport_airports_create(flatbuffers_builder_t *B __gaia_airport_airports_formal_args)
{
    if (gaia_airport_airports_start(B)
        || gaia_airport_airports_gaia_id_add(B, v0)
        || gaia_airport_airports_latitude_add(B, v7)
        || gaia_airport_airports_longitude_add(B, v8)
        || gaia_airport_airports_ap_id_add(B, v1)
        || gaia_airport_airports_name_add(B, v2)
        || gaia_airport_airports_city_add(B, v3)
        || gaia_airport_airports_country_add(B, v4)
        || gaia_airport_airports_iata_add(B, v5)
        || gaia_airport_airports_icao_add(B, v6)
        || gaia_airport_airports_altitude_add(B, v9)
        || gaia_airport_airports_timezone_add(B, v10)
        || gaia_airport_airports_dst_add(B, v11)
        || gaia_airport_airports_tztext_add(B, v12)
        || gaia_airport_airports_type_add(B, v13)
        || gaia_airport_airports_source_add(B, v14)) {
        return 0;
    }
    return gaia_airport_airports_end(B);
}

static gaia_airport_airports_ref_t gaia_airport_airports_clone(flatbuffers_builder_t *B, gaia_airport_airports_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (gaia_airport_airports_start(B)
        || gaia_airport_airports_gaia_id_pick(B, t)
        || gaia_airport_airports_latitude_pick(B, t)
        || gaia_airport_airports_longitude_pick(B, t)
        || gaia_airport_airports_ap_id_pick(B, t)
        || gaia_airport_airports_name_pick(B, t)
        || gaia_airport_airports_city_pick(B, t)
        || gaia_airport_airports_country_pick(B, t)
        || gaia_airport_airports_iata_pick(B, t)
        || gaia_airport_airports_icao_pick(B, t)
        || gaia_airport_airports_altitude_pick(B, t)
        || gaia_airport_airports_timezone_pick(B, t)
        || gaia_airport_airports_dst_pick(B, t)
        || gaia_airport_airports_tztext_pick(B, t)
        || gaia_airport_airports_type_pick(B, t)
        || gaia_airport_airports_source_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, gaia_airport_airports_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, gaia_airport_routes_gaia_id, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), gaia_airport_routes)
__flatbuffers_build_scalar_field(1, flatbuffers_, gaia_airport_routes_gaia_al_id, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), gaia_airport_routes)
__flatbuffers_build_scalar_field(2, flatbuffers_, gaia_airport_routes_gaia_src_id, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), gaia_airport_routes)
__flatbuffers_build_scalar_field(3, flatbuffers_, gaia_airport_routes_gaia_dst_id, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), gaia_airport_routes)
__flatbuffers_build_string_field(4, flatbuffers_, gaia_airport_routes_airline, gaia_airport_routes)
__flatbuffers_build_scalar_field(5, flatbuffers_, gaia_airport_routes_al_id, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), gaia_airport_routes)
__flatbuffers_build_string_field(6, flatbuffers_, gaia_airport_routes_src_ap, gaia_airport_routes)
__flatbuffers_build_scalar_field(7, flatbuffers_, gaia_airport_routes_src_ap_id, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), gaia_airport_routes)
__flatbuffers_build_string_field(8, flatbuffers_, gaia_airport_routes_dst_ap, gaia_airport_routes)
__flatbuffers_build_scalar_field(9, flatbuffers_, gaia_airport_routes_dst_ap_id, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), gaia_airport_routes)
__flatbuffers_build_string_field(10, flatbuffers_, gaia_airport_routes_codeshare, gaia_airport_routes)
__flatbuffers_build_scalar_field(11, flatbuffers_, gaia_airport_routes_stops, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), gaia_airport_routes)
__flatbuffers_build_string_field(12, flatbuffers_, gaia_airport_routes_equipment, gaia_airport_routes)

static inline gaia_airport_routes_ref_t gaia_airport_routes_create(flatbuffers_builder_t *B __gaia_airport_routes_formal_args)
{
    if (gaia_airport_routes_start(B)
        || gaia_airport_routes_gaia_id_add(B, v0)
        || gaia_airport_routes_gaia_al_id_add(B, v1)
        || gaia_airport_routes_gaia_src_id_add(B, v2)
        || gaia_airport_routes_gaia_dst_id_add(B, v3)
        || gaia_airport_routes_airline_add(B, v4)
        || gaia_airport_routes_al_id_add(B, v5)
        || gaia_airport_routes_src_ap_add(B, v6)
        || gaia_airport_routes_src_ap_id_add(B, v7)
        || gaia_airport_routes_dst_ap_add(B, v8)
        || gaia_airport_routes_dst_ap_id_add(B, v9)
        || gaia_airport_routes_codeshare_add(B, v10)
        || gaia_airport_routes_stops_add(B, v11)
        || gaia_airport_routes_equipment_add(B, v12)) {
        return 0;
    }
    return gaia_airport_routes_end(B);
}

static gaia_airport_routes_ref_t gaia_airport_routes_clone(flatbuffers_builder_t *B, gaia_airport_routes_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (gaia_airport_routes_start(B)
        || gaia_airport_routes_gaia_id_pick(B, t)
        || gaia_airport_routes_gaia_al_id_pick(B, t)
        || gaia_airport_routes_gaia_src_id_pick(B, t)
        || gaia_airport_routes_gaia_dst_id_pick(B, t)
        || gaia_airport_routes_airline_pick(B, t)
        || gaia_airport_routes_al_id_pick(B, t)
        || gaia_airport_routes_src_ap_pick(B, t)
        || gaia_airport_routes_src_ap_id_pick(B, t)
        || gaia_airport_routes_dst_ap_pick(B, t)
        || gaia_airport_routes_dst_ap_id_pick(B, t)
        || gaia_airport_routes_codeshare_pick(B, t)
        || gaia_airport_routes_stops_pick(B, t)
        || gaia_airport_routes_equipment_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, gaia_airport_routes_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* AIRPORT_BUILDER_H */
