////////////////////////////////////////////////////
// Copyright (c) Gaia Platform LLC
//
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE.txt file
// or at https://opensource.org/licenses/MIT.
////////////////////////////////////////////////////

#include <iostream>
#include <gaia/db/db.hpp>
#include <gaia/exceptions.hpp>
#include <gaia/logger.hpp>
#include <gaia/system.hpp>
#include <gaia/rules/rules.hpp>

#include "gaia_hospital.h"


using namespace gaia::hospital;
using namespace gaia::rules;
using gaia::common::gaia_id_t;
using gaia::direct_access::auto_transaction_t;

/**
 * Clean the database.
 */
void clean_db()
{
    auto_transaction_t txn(auto_transaction_t::no_auto_restart);
    const bool remove_related_rows = true;

    for (auto doctor_it = doctor_t::list().begin();
         doctor_it != doctor_t::list().end();)
    {
        auto next_doctor_it = doctor_it++;
        next_doctor_it->patients().clear();
        next_doctor_it->delete_row();
    }

    for (auto patient_it = patient_t::list().begin();
         patient_it != patient_t::list().end();)
    {
        auto next_patient_it = patient_it++;
        next_patient_it->delete_row(remove_related_rows);
    }
    for (auto address_it = address_t::list().begin();
         address_it != address_t::list().end();)
    {
        auto next_address_it = address_it++;
        next_address_it->delete_row();
    }

    txn.commit();
}

class example_t
{
public:
    example_t(const char* description)
    {
        gaia_log::app().info(description);
    }

    ~example_t()
    {
        m_transaction.commit();
        // For example purposes only, let all the rules run. 
        sleep(1);
        gaia_log::app().info("Press any key to continue...");
        std::cin.get();
    }

private:
    auto_transaction_t m_transaction;
};

class lesson_t
{
public:
    lesson_t(const char* lesson)
    : m_lesson(lesson)
    {
        clean_db();
        subscribe_ruleset(m_lesson);
    }

    ~lesson_t()
    {
        unsubscribe_ruleset(m_lesson);
    }

private:
    const char* m_lesson;    
};


#define PRINT_METHOD_NAME() gaia_log::app().info("---- {}() ----", __FUNCTION__)

///
/// Direct Access API examples.
///
/// A Direct Access Class (DAC) is a C++ class representing a Gaia database table.
/// DACs are generated by the gaiac and are used to perform CRUD operations
/// on the Gaia database.
///

void run_insert_rule()
{
    example_t example("db: inserting 'Dr. House' to the database");

    doctor_t::insert_row("Dr. House", true);
    
    // Note that we only fire a rule when we add a doctor.
    // We can add a patient as well and no rules are fired.
    patient_writer patient;
    patient.name = "Emma";
    patient.is_active = false;
    patient.insert_row();

    // Note that the transaction must be committed for those changes to
    // be seen by the rules engine. Rules are only fired after the commit.
    // In the examples, the commit call is happening when the 'example_t'
    // class goes out of scope.
}

void run_update_rule()
{
    // In order to reduce boilerplate code, all examples will wrap 
    // transaction handling in the example_t class constructor and
    // destructor from now on.
    example_t example("db: updating patient 'Emma'");

    // Retrieve the first (and only) patient
    patient_t patient = *(patient_t::list().begin());
    patient_writer writer = patient.writer();
    writer.is_active = true;
    writer.update_row();
}



void run_setup_clinic()
{
    // Address IDs
    const uint32_t address_ab_id = 1;
    const uint32_t address_cd_id = 2;
    const uint32_t address_rd_id = 3;
    const uint32_t address_ak_id = 4;
    const uint32_t address_jh_id = 5;
    const uint32_t address_nn_id = 6;

    // In order to reduce boilerplate code, all examples will wrap 
    // transaction handling in the example_t class constructor and
    // destructor from now on.
    example_t example("db: populating clinic");

    // add doctors, patients, and addresses
    doctor_t dr_cox = doctor_t::get(doctor_t::insert_row("Dr. Cox", true));
    doctor_t dr_dorian = doctor_t::get(doctor_t::insert_row("Dr. Dorian", true));
    doctor_t dr_reid = doctor_t::get(doctor_t::insert_row("Dr. Reid", true));

    // Add patients
    patient_t pat_ab = patient_t::get(patient_t::insert_row("Amos Burton", address_ab_id, 71, false, {}));
    patient_t pat_cd = patient_t::get(patient_t::insert_row("Camina Drummer", address_cd_id, 66, false, {}));
    patient_t pat_rd = patient_t::get(patient_t::insert_row("Roberta Draper", address_rd_id, 72, false, {}));
    patient_t pat_ak = patient_t::get(patient_t::insert_row("Alex Kamal", address_ak_id, 68, false, {}));
    patient_t pat_jh = patient_t::get(patient_t::insert_row("Jim Holden", address_jh_id, 73, false, {}));
    patient_t pat_nn = patient_t::get(patient_t::insert_row("Naomi Nagata", address_nn_id, 67, false, {}));

    // Add addresses (1 for each patient).  Because we are using value-linked references we do not need
    // to explicitly connect them.
    address_t add_ab = address_t::get(address_t::insert_row(address_ab_id, "17 Cherry Tree Lane", "Seattle"));
    address_t add_cd = address_t::get(address_t::insert_row(address_cd_id, "350 Fifth Avenue", "New York"));
    address_t add_rd = address_t::get(address_t::insert_row(address_rd_id, "221b Baker St", "Chicago"));
    address_t add_ak = address_t::get(address_t::insert_row(address_ak_id, "1313 Mockingbird Lane", "Georgia"));
    address_t add_jh = address_t::get(address_t::insert_row(address_jh_id, "62 West Wallaby St", "Lansing"));
    address_t add_nn = address_t::get(address_t::insert_row(address_nn_id, "742 Evergreen Terrace", "Springfield"));

    // Connect patients to doctors (each doctor gets two patients) to show
    // explicit relationships (non value-linked).
    dr_cox.patients().connect(pat_ab);
    dr_cox.patients().connect(pat_cd);
    dr_dorian.patients().connect(pat_rd);
    dr_dorian.patients().connect(pat_ak);
    dr_reid.patients().connect(pat_jh);
    dr_reid.patients().connect(pat_nn);
}

void run_navigate_one_to_one()
{
    example_t example("db: making patient active");

    // Make Jim Holden active
    patient_t pat_jh = *(patient_t::list().where(patient_expr::name == "Jim Holden").begin());
    patient_writer writer = pat_jh.writer();
    writer.is_active = true;
    writer.update_row();
}

void run_navigate_one_to_many()
{
    example_t example("db: making doctor inactive");

    // Make Jim Holden active
    doctor_t dr_cox = *(doctor_t::list().where(doctor_expr::name == "Dr. Cox").begin());
    doctor_writer writer = dr_cox.writer();
    writer.is_active = false;
    writer.update_row();
}


int main()
{
    // It is helpful to walk through the direct_access sample before running this one to get
    // acquainted with how to interact with the Gaia database.  This tutorial focuses on
    // the syntax for rules.  Rules are fired in response to changes made to the database.

    // Load up a custom configuration file so that we don't
    // log rule statistics during the tutorial.
    gaia::system::initialize("./gaia_tutorial.conf");

    // By default, all rulesets are subscribed and active after initialization.
    // For this tutorial we'll only subscribe one ruleset at a time per lesson.
    unsubscribe_rules();

    {
        lesson_t lesson("basics");
        run_insert_rule();
        run_update_rule();
    }

    {
        lesson_t lesson("forward_chaining");
        run_insert_rule();
    }

    {
        lesson_t lesson("navigation");
        run_setup_clinic();
        run_navigate_one_to_one();
        run_navigate_one_to_many();        
    }


/*
    create_record_insert();
    create_record_writer();
    lookup_record_get();
    array_type_fields();
    update_record();
    optional_values();
    lookup_invalid_record();
    access_invalid_record();
    compare_records();
    list_all_patients();
    clean_db();
    delete_single_record();
    delete_single_record_static();
    delete_all_records();
    traverse_one_to_many_relationship();
    clean_db();
    delete_one_to_many_relationship_re();
    clean_db();
    delete_one_to_many_relationship();
    clean_db();
    delete_one_to_many_relationship_erase();
    clean_db();
    traverse_one_to_one_relationship();
    clean_db();
    delete_one_to_one_relationship();
    clean_db();
    create_filter_data();
    filter_lambda();
    filter_gaia_predicates_strings();
    filter_gaia_predicates_numbers();
    filter_gaia_predicates_containers();
    clean_db();

    txn.commit();

    use_dac_object_across_transactions();
*/
    gaia::system::shutdown();
}
