name: 'Setup Job'
description: 'Setup a Gaia GHA Job'
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Clean up disk space
      run: |
        df
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        df

    - name: Pull Latest Dev-Core Image
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        #docker pull $DEV_IMAGE
