name: 'Setup Job'
description: 'Setup a Gaia GHA Job'
inputs:
  docker-user:
    description: 'User for Docker'
    required: true
  docker-password:
    description: 'Password for Docker'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.8
      shell: bash
      run: |
        sudo apt --assume-yes update
        sudo apt --assume-yes install software-properties-common
        sudo add-apt-repository --assume-yes ppa:deadsnakes/ppa
        sudo apt --assume-yes install python3.8

    - name: Clean up disk space
      shell: bash
      run: |
        df
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        df

    - name: Pull Latest Dev-Core Image
      shell: bash
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "${{ inputs.docker-password }}" | docker login ghcr.io -u ${{ inputs.docker-user }} --password-stdin
        docker pull $DEV_IMAGE
