/**
 * Gaia School
 * School management system REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * EventApi.h
 *
 *
 */

#ifndef EventApi_H_
#define EventApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "Event.h"
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class EventApi {
public:
  EventApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~EventApi() {}
  void init();

  const std::string base = "/v2";

private:
  void setupRoutes();

  void add_event_handler(const Pistache::Rest::Request &request,
                         Pistache::Http::ResponseWriter response);
  void add_event_participant_handler(const Pistache::Rest::Request &request,
                                     Pistache::Http::ResponseWriter response);
  void delete_event_handler(const Pistache::Rest::Request &request,
                            Pistache::Http::ResponseWriter response);
  void drop_event_participant_handler(const Pistache::Rest::Request &request,
                                      Pistache::Http::ResponseWriter response);
  void get_event_by_id_handler(const Pistache::Rest::Request &request,
                               Pistache::Http::ResponseWriter response);
  void list_event_participant_handler(const Pistache::Rest::Request &request,
                                      Pistache::Http::ResponseWriter response);
  void list_events_handler(const Pistache::Rest::Request &request,
                           Pistache::Http::ResponseWriter response);
  void update_event_handler(const Pistache::Rest::Request &request,
                            Pistache::Http::ResponseWriter response);
  void event_api_default_handler(const Pistache::Rest::Request &request,
                                 Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Add a new event
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="event">Event that needs to be added to the school</param>
  virtual void add_event(const Event &event,
                         Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// Sign-up for an event
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="eventId">ID of the event to signup</param>
  /// <param name="requestBody"> (optional)</param>
  virtual void
  add_event_participant(const int64_t &eventId,
                        const std::vector<int64_t> &requestBody,
                        Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// Remove an event
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="eventId">Id of the event to delete</param>
  virtual void delete_event(const int64_t &eventId,
                            Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// Delete a participant from an event
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="eventId">ID of the event</param>
  /// <param name="studentId">ID of the student</param>
  virtual void
  drop_event_participant(const int64_t &eventId, const int64_t &studentId,
                         Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// Find an event by ID
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="eventId">ID of event to return</param>
  virtual void get_event_by_id(const int64_t &eventId,
                               Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// Find participants of an event
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="eventId">ID of event</param>
  virtual void
  list_event_participant(const int64_t &eventId,
                         Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// List all events
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  virtual void list_events(Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// Update an existing event
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="event">Event that needs to be added to the school</param>
  virtual void update_event(const Event &event,
                            Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* EventApi_H_ */
