/**
 * Gaia School
 * School management system REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Student.h
 *
 * Everything about a student
 */

#ifndef Student_H_
#define Student_H_

#include "Event.h"
#include "Person.h"
#include <nlohmann/json.hpp>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Everything about a student
/// </summary>
class Student {
public:
  Student();
  virtual ~Student();

  void validate();

  /////////////////////////////////////////////
  /// Student members

  /// <summary>
  ///
  /// </summary>
  Person getIdentity() const;
  void setIdentity(Person const &value);
  bool identityIsSet() const;
  void unsetIdentity();
  /// <summary>
  ///
  /// </summary>
  std::vector<Person> &getParents();
  void setParents(std::vector<Person> const &value);
  bool parentsIsSet() const;
  void unsetParents();
  /// <summary>
  ///
  /// </summary>
  std::vector<Event> &getEvents();
  void setEvents(std::vector<Event> const &value);
  bool eventsIsSet() const;
  void unsetEvents();

  friend void to_json(nlohmann::json &j, const Student &o);
  friend void from_json(const nlohmann::json &j, Student &o);

protected:
  Person m_Identity;
  bool m_IdentityIsSet;
  std::vector<Person> m_Parents;
  bool m_ParentsIsSet;
  std::vector<Event> m_Events;
  bool m_EventsIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* Student_H_ */
