/////////////////////////////////////////////
// Copyright (c) Gaia Platform LLC
// All rights reserved.
/////////////////////////////////////////////

// Automatically generated by Gaia EDC code generator, do not modify.

#include "gaia_catalog.h"

namespace gaia {
namespace catalog {

gaia_value_index_t* gaia_field_t::gaia_value_index_owner() {
    gaia_value_index_t* pp = gaia_value_index_t::get_row_by_id(this->m_references[c_parent_gaia_value_index]);
    return pp;
}

}
}
