/////////////////////////////////////////////
// Copyright (c) Gaia Platform LLC
// All rights reserved.
/////////////////////////////////////////////

#include "gtest/gtest.h"

#include "db_test_base.hpp"
#include "file.hpp"

using namespace gaia::db;

class fdw_test : public db_test_base_t
{
    void TearDown() override
    {
        db_test_base_t::TearDown();
    }
};

TEST_F(fdw_test, airport)
{
    // Load the command string generated by the build.
    file_loader_t command_loader;
    command_loader.load_file_data("fdw_test_command.txt");

    char* command = reinterpret_cast<char*>(command_loader.get_data());

    cerr << "Command executed by test is:" << endl << command << endl;

    // Execute the command and validate its return value.
    int return_value = system(command);
    ASSERT_EQ(0, return_value);
}
