/////////////////////////////////////////////
// Copyright (c) Gaia Platform LLC
// All rights reserved.
/////////////////////////////////////////////

// Automatically generated by the Gaia Data Classes code generator.
// Do not modify.

#include "addr_book.h"

namespace gaia
{
namespace addr_book
{

//
// Implementation of class B_t.
//

gaia::common::gaia_id_t B_t::insert_row(const char* str_val, int32_t num_val)
{
    flatbuffers::FlatBufferBuilder b(c_flatbuffer_builder_size);
    b.Finish(internal::CreateBDirect(b, str_val, num_val));
    return edc_object_t::insert_row(b);
}
gaia::direct_access::edc_container_t<c_gaia_type_B, B_t> B_t::list()
{
    return gaia::direct_access::edc_container_t<c_gaia_type_B, B_t>();
}
const char* B_t::str_val() const
{
    return GET_STR(str_val);
}
int32_t B_t::num_val() const
{
    return GET(num_val);
}
A_t B_t::a() const
{
    return A_t::get(this->references()[c_B_parent_a]);
}

//
// Implementation of class A_t.
//

gaia::common::gaia_id_t A_t::insert_row(const char* str_val, int32_t num_val)
{
    flatbuffers::FlatBufferBuilder b(c_flatbuffer_builder_size);
    b.Finish(internal::CreateADirect(b, str_val, num_val));
    return edc_object_t::insert_row(b);
}
gaia::direct_access::edc_container_t<c_gaia_type_A, A_t> A_t::list()
{
    return gaia::direct_access::edc_container_t<c_gaia_type_A, A_t>();
}
const char* A_t::str_val() const
{
    return GET_STR(str_val);
}
int32_t A_t::num_val() const
{
    return GET(num_val);
}
A_t::b_list_t A_t::b() const
{
    return A_t::b_list_t(gaia_id(), c_A_first_b, c_B_next_a);
}

//
// Implementation of class customer_t.
//

gaia::common::gaia_id_t customer_t::insert_row(const char* name, const std::vector<int32_t>& sales_by_quarter)
{
    flatbuffers::FlatBufferBuilder b(c_flatbuffer_builder_size);
    b.Finish(internal::CreatecustomerDirect(b, name, &sales_by_quarter));
    return edc_object_t::insert_row(b);
}
gaia::direct_access::edc_container_t<c_gaia_type_customer, customer_t> customer_t::list()
{
    return gaia::direct_access::edc_container_t<c_gaia_type_customer, customer_t>();
}
const char* customer_t::name() const
{
    return GET_STR(name);
}
gaia::direct_access::edc_vector_t<int32_t> customer_t::sales_by_quarter() const
{
    return GET_ARRAY(sales_by_quarter);
}

//
// Implementation of class internet_contract_t.
//

gaia::common::gaia_id_t internet_contract_t::insert_row(const char* provider, const char* contract_id)
{
    flatbuffers::FlatBufferBuilder b(c_flatbuffer_builder_size);
    b.Finish(internal::Createinternet_contractDirect(b, provider, contract_id));
    return edc_object_t::insert_row(b);
}
gaia::direct_access::edc_container_t<c_gaia_type_internet_contract, internet_contract_t> internet_contract_t::list()
{
    return gaia::direct_access::edc_container_t<c_gaia_type_internet_contract, internet_contract_t>();
}
const char* internet_contract_t::provider() const
{
    return GET_STR(provider);
}
const char* internet_contract_t::contract_id() const
{
    return GET_STR(contract_id);
}
address_t internet_contract_t::address() const
{
    return address_t::get(this->references()[c_internet_contract_parent_address]);
}

//
// Implementation of class phone_t.
//

gaia::common::gaia_id_t phone_t::insert_row(const char* phone_number, const char* type, bool primary)
{
    flatbuffers::FlatBufferBuilder b(c_flatbuffer_builder_size);
    b.Finish(internal::CreatephoneDirect(b, phone_number, type, primary));
    return edc_object_t::insert_row(b);
}
gaia::direct_access::edc_container_t<c_gaia_type_phone, phone_t> phone_t::list()
{
    return gaia::direct_access::edc_container_t<c_gaia_type_phone, phone_t>();
}
const char* phone_t::phone_number() const
{
    return GET_STR(phone_number);
}
const char* phone_t::type() const
{
    return GET_STR(type);
}
bool phone_t::primary() const
{
    return GET(primary);
}
employee_t phone_t::owner() const
{
    return employee_t::get(this->references()[c_phone_parent_owner]);
}
address_t phone_t::address() const
{
    return address_t::get(this->references()[c_phone_parent_address]);
}

//
// Implementation of class address_t.
//

gaia::common::gaia_id_t address_t::insert_row(const char* street, const char* apt_suite, const char* city, const char* state, const char* postal, const char* country, bool current)
{
    flatbuffers::FlatBufferBuilder b(c_flatbuffer_builder_size);
    b.Finish(internal::CreateaddressDirect(b, street, apt_suite, city, state, postal, country, current));
    return edc_object_t::insert_row(b);
}
gaia::direct_access::edc_container_t<c_gaia_type_address, address_t> address_t::list()
{
    return gaia::direct_access::edc_container_t<c_gaia_type_address, address_t>();
}
const char* address_t::street() const
{
    return GET_STR(street);
}
const char* address_t::apt_suite() const
{
    return GET_STR(apt_suite);
}
const char* address_t::city() const
{
    return GET_STR(city);
}
const char* address_t::state() const
{
    return GET_STR(state);
}
const char* address_t::postal() const
{
    return GET_STR(postal);
}
const char* address_t::country() const
{
    return GET_STR(country);
}
bool address_t::current() const
{
    return GET(current);
}
employee_t address_t::owner() const
{
    return employee_t::get(this->references()[c_address_parent_owner]);
}
address_t::internet_contract_list_t address_t::internet_contract() const
{
    return address_t::internet_contract_list_t(gaia_id(), c_address_first_internet_contract, c_internet_contract_next_address);
}
address_t::phones_list_t address_t::phones() const
{
    return address_t::phones_list_t(gaia_id(), c_address_first_phones, c_phone_next_address);
}

//
// Implementation of class employee_t.
//

gaia::common::gaia_id_t employee_t::insert_row(const char* name_first, const char* name_last, const char* ssn, int64_t hire_date, const char* email, const char* web)
{
    flatbuffers::FlatBufferBuilder b(c_flatbuffer_builder_size);
    b.Finish(internal::CreateemployeeDirect(b, name_first, name_last, ssn, hire_date, email, web));
    return edc_object_t::insert_row(b);
}
gaia::direct_access::edc_container_t<c_gaia_type_employee, employee_t> employee_t::list()
{
    return gaia::direct_access::edc_container_t<c_gaia_type_employee, employee_t>();
}
const char* employee_t::name_first() const
{
    return GET_STR(name_first);
}
const char* employee_t::name_last() const
{
    return GET_STR(name_last);
}
const char* employee_t::ssn() const
{
    return GET_STR(ssn);
}
int64_t employee_t::hire_date() const
{
    return GET(hire_date);
}
const char* employee_t::email() const
{
    return GET_STR(email);
}
const char* employee_t::web() const
{
    return GET_STR(web);
}
employee_t employee_t::manager() const
{
    return employee_t::get(this->references()[c_employee_parent_manager]);
}
employee_t::phones_list_t employee_t::phones() const
{
    return employee_t::phones_list_t(gaia_id(), c_employee_first_phones, c_phone_next_owner);
}
employee_t::addresses_list_t employee_t::addresses() const
{
    return employee_t::addresses_list_t(gaia_id(), c_employee_first_addresses, c_address_next_owner);
}
employee_t::reportees_list_t employee_t::reportees() const
{
    return employee_t::reportees_list_t(gaia_id(), c_employee_first_reportees, c_employee_next_manager);
}

} // namespace addr_book
} // namespace gaia
