# Minimal image onto which we can install and test our SDK.
#
# Build:
#   docker build --no-cache -t gaia_sdk -f Dockerfile_gaia_sdk .

FROM gaia_ubuntu20
ARG DEBIAN_FRONTEND=noninteractive

COPY build_sdk_samples.sh .
COPY gaia-0.1.0_amd64.deb .

RUN apt install ./gaia-0.1.0_amd64.deb
RUN sh ./build_sdk_samples.sh
