global_pattern = "[%Y-%m-%dT%T%z] [%l] [%P %t] <%n>: %v"

[[sink]]
name = "console"
type = "stdout_sink_mt"

[[sink]]
name = "file_rotating"
type = "rotating_file_sink_mt"
base_filename = "logs/gaia.log"
max_size = "1M"
max_files = 10
create_parent_dir = true

[[sink]]
name = "syslog"
type = "syslog_sink_mt"
# Generally no need to fill in the optional fields below.
# ident = "" (default)
# syslog_option = 0 (default)
# syslog_facility = LOG_USER (default macro value)

[[logger]]
name = "gaia-root"
sinks = [
    "console",
    "file_rotating",
    "syslog"
]
level = "info"
