global_pattern = "[%Y-%m-%dT%T%z] [%l] [%P %t] <%n>: %v"

[[sink]]
name = "console"
type = "stdout_sink_mt"
level = "trace"

[[sink]]
name = "file_rotating"
type = "rotating_file_sink_mt"
base_filename = "log/gaia.log"
max_size = "1M"
max_files = 10
create_parent_dir = true
level = "trace"

[[sink]]
name = "syslog"
type = "syslog_sink_mt"
level = "trace"
# generally no need to fill up the optional fields below
# ident = "" (default)
# syslog_option = 0 (default)
# syslog_facility = LOG_USER (default macro value)

[[logger]]
name = "root"
sinks = [
    "console",
    "file_rotating",
    "syslog"
]
level = "trace"