name: 'Setup Action'
description: 'Setup a Gaia GHA Job'
inputs:
  docker-user:
    description: 'User for Docker'
    required: true
  docker-password:
    description: 'Password for Docker'
    required: true
runs:
  using: "composite"
  steps:
# - name: Setup Python 3.8
#   shell: bash
#   run: |
#     sudo apt --assume-yes update
#     sudo apt --assume-yes install software-properties-common
#     sudo add-apt-repository --yes ppa:deadsnakes/ppa
#     sudo apt --assume-yes install python3.8
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Clean up disk space
      shell: bash
      run: |
        echo "Before Any Cleanup"
        df -h
        sudo rm -rf /usr/share/dotnet
        echo "After Dotnet Cleanup ~ 4G"
        df -h
        sudo rm -rf /opt/ghc
        echo "After Haskell Cleanup ~0.5G"
        df -h
        sudo rm -rf /usr/local/lib/android
        echo "After Android Cleanup ~15G"
        df -h

    - name: Pull Latest Dev-Core Image
      shell: bash
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "${{ inputs.docker-password }}" | docker login ghcr.io -u ${{ inputs.docker-user }} --password-stdin
        docker pull $DEV_IMAGE
