#!/bin/bash

# TODO: check for clang-format version.

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

# check if clang-format is installed. If not, gives the option to install it (on debian based systems)
if ! command -v clang-format &> /dev/null
then
  if [ ! -f "/etc/debian_version" ];
  then
    ehco "Please install clang-format 10.0"
    exit 1
  fi

  while true
  do
    read -rp "clang-format could not be found, do you wish to install it? [y/n]: " yn
    case $yn in
        [Yy]* ) sudo apt-get install clang-format; break;;
        [Nn]* ) exit 1;;
    esac
  done
fi

# Runs clang-format only on files that:
# 1. Are in the index (git add)
# 2. Are in the production/ directory
# 3. End with .hpp/.cpp
for file in $(git diff --no-pager --cached --name-only | grep -E "^production.*(.hpp|.cpp)")
do
  clang-format -i "$file"
  git add "$file"
done
