#!/bin/bash

# TODO: check for clang-format version.

# Allows us to read user input below, assigns stdin to keyboard
exec </dev/tty

# check if clang-format is installed.
if ! command -v clang-format &>/dev/null; then
    ehco "Please install clang-format 10.0"
    exit 1
fi

# Files excluded from clang-format (interpreted as regex against the full path of the file)
excluded_files=(
    "gaia_catalog\.h"
    "catalog_generated\.h"
)

# Runs clang-format only on files that:
# 1. Are in the index (git add)
# 2. Are in the production/ directory
# 3. End with .hpp/.cpp
for file in $(git --no-pager diff --cached --name-only | grep -E "^production.*(.hpp|.cpp|.h|.inc)"); do
    format_file=true

    for exclude_pattern in "${excluded_files[@]}"; do
        if echo "$file" | grep -qE "$exclude_pattern"; then
            format_file=false
            break
        fi
    done

    if [ "$format_file" = "true" ]; then
        clang-format -i "$file"
        git add "$file"
    fi
done
