#!/bin/bash

# TODO: check for clang-format version.

# Allows us to read user input below, assigns stdin to keyboard
exec </dev/tty

# check if clang-format is installed.
if ! command -v clang-format &>/dev/null; then
    echo "Please install clang-format 10.0"
    exit 1
fi

# Files excluded from clang-format (interpreted as regex against the full path of the file)
excluded_files=(
    "gaia_catalog\.h"
    "catalog_generated\.h"
)

# Runs clang-format only on files that:
# 1. Are in the index (git add)
# 2. Are in the production/ directory
# 3. End with .hpp/.cpp/etc..
for file in $(git --no-pager diff --cached --name-only | grep -E "^production.*(\.hpp|\.cpp|\.inc)$|^\.clang-format$"); do
    format_file=true

    if [ ! -f "$file" ]; then
      continue
    fi

    for exclude_pattern in "${excluded_files[@]}"; do
        if echo "$file" | grep -qE "$exclude_pattern"; then
            format_file=false
            break
        fi
    done

    # If .clang-format has been changed, formats clang_format.cpp/hpp to show the outcome.
    if echo "$file" | grep -qE "(\.clang-format)$"; then
        clang-format -i "production/tools/gaia_style/tests/clang_format.cpp"
        git add "production/tools/gaia_style/tests/clang_format.cpp"
        clang-format -i "production/tools/gaia_style/tests/clang_format.hpp"
        git add "production/tools/gaia_style/tests/clang_format.hpp"
        format_file=false
    fi

    if [ "$format_file" = "true" ]; then
        echo "Formatting file: $file"
        clang-format -i "$file"
        git add "$file"
    fi
done
