# Title:      Coverage Job Action
# Purpose:    To build a full version of the product and measure code coverage and other metrics.
# Prereqs:    - `./.github/actions/setup-job`
# Inputs:     - `gaia-repo` - root of the GAIA repository on the file system
#             - `job-name` - name of the job that contains the call to this action
# Notes:      - None
---
name: 'Coverage Job'
description: 'Build the product and measure the testing done against the product.'
inputs:
  gaia-repo:
    description: 'Repository location'
    required: true
  job-name:
    description: 'Name of the job this is being called from'
    required: true
runs:
  using: "composite"
  steps:

    - name: Coverage
      shell: bash
      run: |
        cd ${{ inputs.gaia-repo }}/production
        mkdir -p ${{ inputs.gaia-repo }}/production
        sudo chmod -R 777 ${{ inputs.gaia-repo }}/production
        mkdir -p ${{ inputs.gaia-repo }}/build/output
        sudo chmod -R 777 ${{ inputs.gaia-repo }}/build/output
        ${{ inputs.gaia-repo }}/production/coverage/coverage.sh --verbose --output ${{ inputs.gaia-repo }}/build/output
        cp ${{ inputs.gaia-repo }}/production/raw_dockerfile ${{ inputs.gaia-repo }}/build/output
        cp ${{ inputs.gaia-repo }}/production/dockerfile ${{ inputs.gaia-repo }}/build/output
        echo "sudo chmod -R 777 ${{ inputs.gaia-repo }}/production"
        sudo chmod -R 777 ${{ inputs.gaia-repo }}/production

    - name: Upload Output Files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.job-name }} Test Files
        path: |
          ${{ inputs.gaia-repo }}/production/output
