# Title:      Third Party Job Action
# Purpose:    To build the third-party part of the product, the things that do not
#             change across build flavors.
# Prereqs:    - `./.github/actions/setup-job`
# Inputs:     - `gaia-repo` - root of the GAIA repository on the file system
#             - `job-name` - name of the job that contains the call to this action
# Notes:      - None
---
name: 'Third Party Job'
description: 'Build the common parts of the product and artifact/publish them.'
inputs:
  gaia-repo:
    description: 'Repository location'
    required: true
  job-name:
    description: 'Name of the job this is being called from'
    required: true
runs:
  using: "composite"
  steps:

    - name: Build Docker Image
      shell: bash
      run: |
        cd ${{ inputs.gaia-repo }}/production
        pip install atools argcomplete
        ${{ inputs.gaia-repo }}/dev_tools/gdev/gdev.sh dockerfile > ${{ inputs.gaia-repo }}/production/raw_dockerfile
        ${{ inputs.gaia-repo }}/dev_tools/github-actions/copy_until_line.py \
          --input-file ${{ inputs.gaia-repo }}/production/raw_dockerfile \
          --output-file ${{ inputs.gaia-repo }}/production/dockerfile \
          --stop-line "# GenRunDockerfile(production)"
        docker buildx build \
          -f ${{ inputs.gaia-repo }}/production/dockerfile \
          -t $DEV_IMAGE \
          --cache-from $DEV_IMAGE \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --platform linux/amd64 \
          --shm-size 1gb \
          --ssh default \
          --compress \
          ..

    - name: Upload Intermediate Files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.job-name }} Output Files
        path: |
          ${{ inputs.gaia-repo }}/production/raw_dockerfile
          ${{ inputs.gaia-repo }}/production/dockerfile

    - name: Publish Dev Image to GitHub Repository
      shell: bash
      run: |
        echo "Pushing Dev Image to GitHub Docker Repository"
        docker push $DEV_IMAGE

    - name: Save Compressed Dev Image
      shell: bash
      run: |
        echo "Saving Dev Image as GZipped Tarball"
        docker save $DEV_IMAGE | gzip > ${{ inputs.gaia-repo }}/production/dev_image.tar.gz
        ls -la ${{ inputs.gaia-repo }}/production/dev_image.tar.gz

    - name: Upload Compressed Dev Image
      uses: actions/upload-artifact@v2
      with:
        name: Dev Image
        path: |
          ${{ inputs.gaia-repo }}/production/dev_image.tar.gz
