name: 'Lint Job'
description: 'Lint the entire repository and ensure that it follows all guidelines.'
inputs:
  event-name:
    description: 'Name associated with the event'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Required Python Packages
      shell: bash
      run: |
        python3 -m pip install pre-commit

    - name: Set Cache Key for Pre-Commit Checks
      shell: bash
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

    - name: Apply Pre-Commit Checks Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Execute Pre-Commit Checks
      shell: bash
      run: |
        cd $GAIA_REPO/production
        pre-commit run --all-files

    - name: GitHub Info
      shell: bash
      run: |
        echo "Event-Name: ${{ inputs.event_name }}"
