# Title:      Build Job Action
# Purpose:    To coordinate the building and publishing of a build with a given flavor.
# Prereqs:    - `./.github/actions/setup-job`
# Inputs:     - `gaia-repo` - root of the GAIA repository on the file system
#             - `job-name` - name of the job that contains the call to this action
#             - `execute-unit-tests` - set to `true` to execute unit tests after the build is complete
#             - `publish-package` - set to `true` to create a package and publish it to the job's artifacts
#             - `build-flavor` - flavor to associate with the build (passed on to `gdev` as `cfg-enables`)
# Notes:      - None
---
name: 'Build Job'
description: 'Build one of the flavors of a Gaia build.'
inputs:
  gaia-repo:
    description: 'Repository location'
    required: true
  job-name:
    description: 'Name of the job this is being called from'
    required: true
  execute-unit-tests:
    description: 'Set to "true" to execute unit tests'
    required: false
    default: 'true'
  publish-package:
    description: 'Set to "true" to publish a generated package'
    required: false
    default: 'false'
  build-flavor:
    description: 'Configuration to pass to GDev'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
  
    - name: Build Docker Image
      shell: bash
      run: |
        CFG_ENABLES=
        if [ "${{ inputs.build-flavor }}" != "" ] ; then
          CFG_ENABLES="--cfg-enables ${{ inputs.build-flavor }}"
        fi
        echo "Configuration: $CFG_ENABLES"
        $GAIA_REPO/dev_tools/github-actions/build_image.sh \
            --verbose \
            --repo-path $GAIA_REPO \
            --base-image $DEV_IMAGE $CFG_ENABLES

    - name: Run Unit Tests
      shell: bash
      run: |
        if [ "${{ inputs.execute-unit-tests }}" == "true" ] ; then
          $GAIA_REPO/dev_tools/github-actions/post_build_action.sh \
            --verbose \
            --repo-path $GAIA_REPO \
            --action unit_tests
        fi

    - name: Publish Debian Package
      shell: bash
      run: |
        if [ "${{ inputs.publish-package }}" == "true" ] ; then
          $GAIA_REPO/dev_tools/github-actions/post_build_action.sh \
            --verbose \
            --repo-path $GAIA_REPO \
            --action publish_package
        fi

    - name: Upload Install Package
      if: ${{ inputs.publish-package == 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.job-name }} Install Package
        path: |
          ${{ inputs.gaia-repo }}/build/output/package

    - name: Upload Output Files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.job-name }} Output Files
        path: |
          ${{ inputs.gaia-repo }}/build/output
