# Install the SDK built for Ubuntu 18.04, build, and execute the samples.
#
# Build:
#   docker build --no-cache -t gaia_sdk_18 -f Dockerfile_gaia_sdk_18 .

FROM gaia_ubuntu_18
ENV DEBIAN_FRONTEND=noninteractive

COPY build_sdk_samples.sh .
COPY gaia-0.2.1_amd64.deb .

ENV CC=/usr/bin/clang-10
ENV CPP=/usr/bin/clang-cpp-10
ENV CXX=/usr/bin/clang++-10
ENV LDFLAGS=-fuse-ld=lld-10

RUN apt-get update \
    && apt-get install -y ./gaia-0.2.1_amd64.deb
RUN /bin/bash ./build_sdk_samples.sh
