# Install the SDK built for Ubuntu 20.04, build, and execute the samples.
#
# Build:
#   docker build --no-cache -t gaia_sdk_20 -f Dockerfile_gaia_sdk_20 .

FROM gaia_ubuntu_20
ENV DEBIAN_FRONTEND=noninteractive

ARG gaia_sdk_deb

COPY build_sdk_samples.sh .
COPY $gaia_sdk_deb .

ENV CC=/usr/bin/clang-10
ENV CPP=/usr/bin/clang-cpp-10
ENV CXX=/usr/bin/clang++-10

RUN echo gaia gaia/install-service boolean false | debconf-set-selections
RUN apt-get update \
    && apt-get install ./$gaia_sdk_deb
RUN ldconfig
RUN /bin/bash ./build_sdk_samples.sh
