# Install the SDK built for Ubuntu 18.04, build, and execute the samples.
#
# Build:
#   docker build --no-cache -t gaia_sdk_18 -f Dockerfile_gaia_sdk_18 .

FROM gaia_ubuntu_18
ENV DEBIAN_FRONTEND=noninteractive

COPY build_sdk_samples.sh .
COPY gaia-0.1.0_amd64.deb .

RUN apt install ./gaia-0.1.0_amd64.deb
RUN /bin/bash ./build_sdk_samples.sh
