# Install the SDK built for Ubuntu 20.04, build, and execute the samples.
#
# Build:
#   docker build --no-cache -t gaia_sdk_20 -f Dockerfile_gaia_sdk_20 .

FROM gaia_ubuntu_20
ENV DEBIAN_FRONTEND=noninteractive

COPY build_sdk_samples.sh .
COPY gaia-0.1.0_amd64.deb .

RUN apt install ./gaia-0.1.0_amd64.deb
RUN /bin/bash ./build_sdk_samples.sh
