# Minimal Ubuntu 18.04 image onto which we can install and test our SDK.
#
# Build:
#   docker build -t gaia_ubuntu_18 -f Dockerfile_gaia_ubuntu_18 .

FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y \
  wget \
  make \
  clang-10 \
  lld-10 \
  && apt-get clean

ENV CC=/usr/bin/clang-10
ENV CPP=/usr/bin/clang-cpp-10
ENV CXX=/usr/bin/clang++-10
ENV LDFLAGS="-B/usr/lib/llvm-10/bin/ -fuse-ld=lld"

# Install newer version of cmake than is available by default on Ubuntu 18.04.
RUN mkdir ~/temp \
  && cd ~/temp \
  && wget https://github.com/Kitware/CMake/releases/download/v3.18.6/cmake-3.18.6.tar.gz \
  && tar -xzvf cmake-3.18.6.tar.gz > /dev/null \
  && cd cmake-3.18.6/ \
  && ./bootstrap -- -DCMAKE_USE_OPENSSL=OFF \
  && make -j4 \
  && make install
