# System wide settings.

[System]
logger_config = "./log_conf.toml"

# Settings for the database.
[Database]

# Settings for the catalog.
[Catalog]

# Settings for the rules engine.
[Rules]
# Number of threads used by the rules engine to execute rules
# Use -1 to indicate that the engine should use the number
# of available hardware threads. Note that the rules engine
# must use at least one thread so a value of 0 is invalid.
thread_count = -1

# Interval in seconds of how frequently the rules engine logs statistics.
# If the value is set to 0 then no statistics will be logged to the
# gaia_stats log file.
stats_log_interval = 30

# The rules engine always calculates cumulative statistics for all rules.
# If this setting is set to true, then the rules engine will also calculate 
# statistics for each individual rule and log them to the statistics log file.
log_individual_rule_stats = false

# Number of times the rules engine should retry a rule when
# an update conflict is encountered
rule_retry_count = 3
