name: Remove old artifacts

on:
  schedule:
    # Every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '14 days'
        skip-recent: 5
